version: "3.8"
services:
  backend-flask:
    environment:
      #AWS_ENDPOINT_URL: "http://dynamodb-local:8000"
      PROD_CONNECTION_URL: 'postgresql://cruddurroot:Password999!@cruddur-db-instance.cyzqxlnlmrnn.ap-southeast-1.rds.amazonaws.com:5432/cruddur'
      CONNECTION_URL: "postgresql://postgres:password@db:5432/cruddur"
      NO_DB_CONNECTION_URL: "postgresql://postgres:password@db:5432"
      PROD_NO_DB_CONNECTION_URL: 'postgresql://cruddurroot:Password999!@cruddur-db-instance.cyzqxlnlmrnn.ap-southeast-1.rds.amazonaws.com:5432' 
      FRONTEND_URL: "https://3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      OTEL_SERVICE_NAME: "backend-flask"
      OTEL_EXPORTER_OTLP_ENDPOINT: "https://api.honeycomb.io"
      OTEL_EXPORTER_OTLP_HEADERS: "x-honeycomb-team=${HONEYCOMB_API_KEY}"
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      ROLLBAR_ACCESS_TOKEN: "${ROLLBAR_ACCESS_TOKEN}"
      AWS_XRAY_URL: "*4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}*"
      AWS_XRAY_DAEMON_ADDRESS: "xray-daemon:2000"
      AWS_COGNITO_USER_POOL_ID: "ap-southeast-1_nioDMKtYf"
      AWS_COGNITO_USER_POOL_CLIENT_ID: "4gl2o58o33odv56d0rsmneqeo9"
      PYTHONUNBUFFERED: 1
    build: ./backend-flask
    ports:
      - "4567:4567"
    volumes:
      - ./backend-flask:/backend-flask
  frontend-react-js:
    environment:
      REACT_APP_BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      REACT_APP_OTEL_COLLECTOR_URL: "https://4318-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      REACT_APP_AWS_PROJECT_REGION: "${AWS_DEFAULT_REGION}"
      REACT_APP_AWS_COGNITO_REGION: "${AWS_DEFAULT_REGION}"
      REACT_APP_AWS_USER_POOLS_ID: "ap-southeast-1_nioDMKtYf"
      REACT_APP_CLIENT_ID: "4gl2o58o33odv56d0rsmneqeo9"
    build: 
      context: ./frontend-react-js
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  dynamodb-local:
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal    
volumes:
  db:
    driver: local
networks:
  internal-network:
    driver: bridge
    name: cruddur    
  # dynamodb-local:
  #   user: root
  #   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
  #   image: "amazon/dynamodb-local:latest"
  #   container_name: dynamodb-local
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - "./docker/dynamodb:/home/dynamodblocal/data"
  #   working_dir: /home/dynamodblocal
#  xray-daemon:
#    image: "amazon/aws-xray-daemon"
#    environment:
#      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
#      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
#      AWS_REGION: "us-east-1"
#    command:
#      - "xray -o -b xray-daemon:2000"
#    ports:
#      - 2000:2000/udp 
#  otel-collector:
#    environment:
#      FRONTEND_URL_HTTPS: "https://3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
#      FRONTEND_URL_HTTP: "http://3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
#    image: otel/opentelemetry-collector
#    command: [--config=/conf/otel-collector-config.yaml]
#    volumes:
#      - ./otel-collector-config.yaml:/conf/otel-collector-config.yaml
#    ports:
#      - 4317:4317 # OTLP gRPC receiver
#      - 4318:4318 # OTLP http receiver  



