[deploy]
bucket = 'cfn-artifacts-cruddur.in'
region = 'ap-southeast-1'
nstack_name = 'CrdNet'
cstack_name = 'CrdCluster'
sstack_name = 'CrdService'
rdsstack_name = 'CrdRDS'
cicdstack_name = 'CrdCiCd'
fstack_name = 'CrdFrontend'
muserstack_name = 'CrdMachineuser'

[parameters]
AcmCertificate = 'arn:aws:acm:us-east-1:623053391718:certificate/5bb23926-5b53-4c8d-be37-0595d513bdcf'
NetworkingStack = 'CrdNet'
ClusterStack = 'CrdCluster'
ServiceStack = 'CrdService'
RdsStack = 'CrdRDS'
Region = 'ap-southeast-1'
AccountID = '623053391718'
CertID = '327f532d-3fb0-4461-9fa5-4f5a866016a2'
ServiceName = 'backend-flask'
FrontendUrl = 'https://cruddur.in'
BackendUrl = 'https://api.cruddur.in'
AWSCognitoUserPoolId = 'ap-southeast-1_nioDMKtYf'
AWSCognitoUserPoolClientId = '4gl2o58o33odv56d0rsmneqeo9'
EcrImage = '623053391718.dkr.ecr.ap-southeast-1.amazonaws.com/backend-flask'
HostedZoneId = 'Z0887069LX6AP47F67RT'
DomainName = 'cruddur.in'
AlternativeDomainName = '*.cruddur.in'
FEPort = 3000
BEPort = 4567
DBMasterUsername = 'cruddurroot'
DBMasterUserPwd = 'Password999'
DBName = 'cruddur'
GitHubBranch = 'prod'
GitHubRepo = 'samba73/aws-bootcamp-cruddur-2023'
RootDomainName = 'cruddur.in'
ArtifactStoreS3 = 'codedeploy-cruddur.in'
BuildSpec = 'backend-flask/buildspec.yml'
DDB_TABLENAME = 'cruddur-message'
