#! /usr/bin/env bash
set -e
CYAN='\033[1;36m'
NO_COLOR='\033[0m'
LABEL="Create Cluster for Cruddur using CFN"
printf "${CYAN}== ${LABEL}${NO_COLOR}\n"
printf "hello"
ABS_PATH=$(readlink -f "$0")
DDB_PATH=$(dirname $ABS_PATH)
TEMPL_PATH="$DDB_PATH/template.yaml"
ARTIFACT_BUCKET="cfn-artifacts-cruddur.in"
OUTPUT_TEMPL_PATH="/workspace/aws-bootcamp-cruddur-2023/.aws-sam/build/packaged.yaml"
SAM_PATH=$(dirname $DDB_PATH)
PROJ_PATH=$(dirname $SAM_PATH)
CONFIG_PATH="PROJ_PATH/aws/cfn/config.toml"

echo "== package"
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-package.html
sam package \
  --s3-bucket $ARTIFACT_BUCKET \
  --s3-prefix ddb \
  --config-file $CONFIG_PATH \
  --output-template-file $OUTPUT_TEMPL_PATH \
  --template-file $TEMPL_PATH \
