#!/usr/bin/bash
set -e
CYAN='\033[1;36m'
NO_COLOR='\033[0m'
LABEL="DDB CFN setup"
printf "${CYAN}== ${LABEL}${NO_COLOR}\n"

ABS_PATH=$(readlink -f "$0")
DDB_PATH=$(dirname $ABS_PATH)
printf $DDB_PATH
source "$DDB_PATH/build"
source "$DDB_PATH/package"
source "$DDB_PATH/deploy"