AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: |
  - Create DDB table
  - Create DDB Stream
Parameters:
  ReadCapacityUnits:
    Type: Number
    Default: 5
  WriteCapacityUnits:
    Type: Number
    Default: 5
  DeletionProtectionEnabled:
    Type: String
    Default: false
  LambdaRuntime:
    Type: String
    Default: python3.9
  MemorySize:
    Type: Number
    Default: 128
  Timeout:
    Type: Number  
    Default: 3
  TableName:
    Type: String  
Resources:
  CruddurDDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: message_group_uuid
          AttributeType: S
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      TableName: !Ref TableName    
      TableClass: STANDARD
      KeySchema: 
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput: 
        ReadCapacityUnits: !Ref ReadCapacityUnits
        WriteCapacityUnits: !Ref WriteCapacityUnits
      DeletionProtectionEnabled: !Ref DeletionProtectionEnabled
      StreamSpecification:
        StreamViewType: NEW_IMAGE    
      GlobalSecondaryIndexes:
           - IndexName: message-group-sk-index
             KeySchema:
                  - AttributeName: message_group_uuid
                    KeyType: HASH
                  - AttributeName: sk
                    KeyType: RANGE
             Projection:
              ProjectionType: ALL
             ProvisionedThroughput: 
                ReadCapacityUnits: !Ref ReadCapacityUnits
                WriteCapacityUnits: !Ref WriteCapacityUnits 
  ProcessDynamoDBStream:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cruddur-messaging-stream
      PackageType: Zip
      Handler: lambda_handle
      Runtime: !Ref LambdaRuntime
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: !Ref MemorySize
      Timeout: !Ref Timeout
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt CruddurDDBTable.StreamArn
            BatchSize: 1
            StartingPosition: LATEST   
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/cruddur-ddb-message
  LambdaLogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref LambdaLogGroup
      LogStreamName: DDBLambda                      
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CruddurDDBStreamExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: logs:CreateLogGroup
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${LambdaLogGroup}:*"
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                Resource: "*"
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"
              - Effect: Allow
                Action:
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource: "*"
Outputs:
    DDBTable:
      Value: !Ref CruddurDDBTable
      Export:
        Name: !Sub '${AWS::StackName}DDBTable'

