FROM 623053391718.dkr.ecr.ap-southeast-1.amazonaws.com/cruddur-python:latest    

WORKDIR /backend-flask

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .


ENV ROLLBAR_ACCESS_TOKEN='644e2ee76ca64c2eb5cbc5f1c7021483'

EXPOSE ${PORT}

CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0", "--port=4567","--no-debug", "--no-debugger", "--no-reload" ]