export AWS_DEFAULT_REGION='ap-southeast-1'
gp env AWS_DEFAULT_REGION='ap-southeast-1'

export AWS_ACCESS_KEY_ID='AKIAZCEHAI5TLFIQZRZ7'
gp env AWS_ACCESS_KEY_ID='AKIAZCEHAI5TLFIQZRZ7'

export AWS_SECRET_ACCESS_KEY='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'
gp env AWS_SECRET_ACCESS_KEY='6dZxFLVahr1Jd4ny0t9g2vbids3tFiDGXK1qrOGT'

