#!/usr/bin/bash
set -e

ECR_BACKEND_FLASK_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/backend-flask
PATH=$(realpath .)/backend-flask

docker build -f $PATH/Dockerfile.prod -t backend-flask:latest  .
sleep 30 &
echo $!
docker tag backend-flask:latest $ECR_BACKEND_FLASK_URL:latest
sleep 10 &
echo $!
docker push $ECR_BACKEND_FLASK_URL:latest
sleep 10 &
echo $?