FROM node:16.18 as build

ENV PORT=3000

WORKDIR /frontend-react-js

COPY . /frontend-react-js

RUN npm install

RUN npm run build

FROM nginx

EXPOSE ${PORT}

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=build /frontend-react-js/build /usr/share/nginx/html