#!/usr/bin/env python3

import urllib.request

try:
    response = urllib.request.urlopen('http://localhost:4568/api/health_check')
    print(response.getcode())
    if response.getcode() == 200:
        print('Flask server is running')
        #exit(0)
    else:
        print('Flask server is not running')
        exit(1)    
except Exception() as e:
    print('Exception occured', e)        
    exit(1)