name: Frontend Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - run: cd frontend-react-js
      - run: npm install
      - run: npm install aws-amplify,
      - run: npm install dotenv@16.1.3,
      - run: npm install js-cookie@3.0.1,
      - run: npm install react@18.2.0,
      - run: npm install react-dom@18.2.0,
      - run: npm install react-router-dom@6.11.2,
      - run: npm install react-scripts@5.0.1
      - run: cat package.json



